# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fagfit_cpp <- function(surv2, covar2, strata2, weights, offset, ibeta, sort1, sort2, method, maxiter, eps, H, Dstar, G, lambda, gamma, M, d, n_npvar, Dnrow, penalty_where, doscale, f, df_f) {
    .Call(`_fcoxph_fagfit_cpp`, surv2, covar2, strata2, weights, offset, ibeta, sort1, sort2, method, maxiter, eps, H, Dstar, G, lambda, gamma, M, d, n_npvar, Dnrow, penalty_where, doscale, f, df_f)
}

fcoxfit_cpp <- function(time, status, covar2, offset, weights, strata2, maxiter, eps, H, Dstar, G, method, ibeta, lambda, gamma, M, d, n_npvar, Dnrow, penalty_where, doscale, f, df_f) {
    .Call(`_fcoxph_fcoxfit_cpp`, time, status, covar2, offset, weights, strata2, maxiter, eps, H, Dstar, G, method, ibeta, lambda, gamma, M, d, n_npvar, Dnrow, penalty_where, doscale, f, df_f)
}

