# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Score <- function(n, method, time, status, strata, score, wt) {
    .Call(`_fcoxph_Score`, n, method, time, status, strata, score, wt)
}

